version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: gunicorn --reload -b 0.0.0.0:8000 maxmilhas_challenge.wsgi
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
