# Generated by Django 2.0 on 2017-12-07 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=14, unique=True)),
            ],
            options={
                'verbose_name': 'CPF',
                'verbose_name_plural': 'CPFs',
            },
        ),
        migrations.CreateModel(
            name='CPFBlacklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('cpf', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cpf.CPF')),
            ],
            options={
                'verbose_name': 'CPF Blacklist',
                'verbose_name_plural': 'CPFs Blacklist',
            },
        ),
    ]
