# Generated by Django 2.0 on 2017-12-07 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cpf',
            options={'verbose_name': 'CPF', 'verbose_name_plural': 'CPFs'},
        ),
        migrations.AlterModelOptions(
            name='cpf_blacklist',
            options={'verbose_name': 'Blacklisted CPF', 'verbose_name_plural': 'Blacklisted CPFs'},
        ),
    ]
