# Generated by Django 2.0 on 2017-12-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cpfblacklist',
            options={'verbose_name': 'Blacklisted CPF', 'verbose_name_plural': 'Blacklisted CPFs'},
        ),
        migrations.AlterField(
            model_name='cpf',
            name='number',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
